#!/bin/sh
# commits current changes to master (via commit -a) and calls the deploy script which pushes to gh-pages
# note that with neither script does master get pushed
[ `git rev-parse --abbrev-ref HEAD` != "master" ] && echo "Not on master branch. Aborting" && exit 1
if [[ -z $1 ]] 
then
	echo "No args supplied, using default commit message"
	git commit -a -m"\"commitdeploy\" scripted commit on master performed on host `hostname` at `date`" && ./deploy
else 
	echo "Using provided argument list as commit message"
	git commit -a -m"$*" && ./deploy
fi