#!/bin/bash
# run me to deploy to gh-pages (don't use pre/postcommit hook... it's too inflexible) 
[ `git rev-parse --abbrev-ref HEAD` != "master" ] && echo "Not on master branch. Aborting" && exit 1
git checkout gh-pages
git pull
git merge -Xtheirs master --no-commit # favor master (as that is where *all* dev occurs; gh-pages is where auto-edits occur)
# update the js file with commit identification information from git
sed -i_bak "s/#%.*%#/#% `git log master -1 --format="%h %s"` %#/" debug.js
git add debug.js
rm debug.js_bak
git commit -m"script writes git hash into js file for this commit: `git log master -1 --format="%h %s"`"
git checkout master
git push origin gh-pages